apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "AddMyTeam"
  annotations:
    github.com/project-slug: t-maoshengye/add-my-team-by-terraform
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"
